#!/usr/bin/env python

import csv
from Bio import SeqIO
import os

##### Configuration #####

if config.get("force"):
    config["force"] = "--forceall "

if config["quiet_mode"]=="True":
    config["quiet_mode"] = "--quiet"
else:
    config["quiet_mode"] = ""



config["distance"]=int(config["distance"])

if config["qc_fail"] != "":
    fail_file = config["qc_fail"]
    config["qc_fail"] = f"--failed-seqs {fail_file}"

##### Target rules #####
if config["report"] =="True":
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"],"local_trees","collapse_report.txt"),
            os.path.join(config["outdir"], "llama_report.md")
else:
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"],"local_trees","collapse_report.txt")



##### Modules #####
include: "assess_putative_lineage.smk"
